# Generated by Django 5.1.4 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='robot',
        ),
        migrations.AddField(
            model_name='order',
            name='robot_serial',
            field=models.CharField(default='default robot', max_length=5),
            preserve_default=False,
        ),
    ]
